
server:
  port: 8081
spring:
  datasource:
    continue-on-error: true
    initialization-mode: always
    initialize: true
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/Ecommerce_DB
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



